<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>AppService_HomeService.Domain.AppService</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\02.Infrastructure\DataAccess-HomeService.Infra.Data.Repo.EFCore\HomeService.Infra.Repo.EFCore\HomeService.Infra.Repo.EFCore.csproj" />
    <ProjectReference Include="..\..\..\Core-HomeService.Domain.Core\Core-HomeService.Domain.Core\Core-HomeService.Domain.Core.csproj" />
  </ItemGroup>

</Project>
