// <auto-generated />
using System;
using Core_HomeService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeService.Infra.SqlServer.EFCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251226061809_addingPropertyToSubCategory")]
    partial class addingPropertyToSubCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core_HomeService.Domain.Core.CategoryAgg.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "دکوراسیون ساختمان"
                        },
                        new
                        {
                            Id = 2,
                            Name = "تاسیسات ساختمان"
                        },
                        new
                        {
                            Id = 3,
                            Name = "وسایل نقلیه"
                        },
                        new
                        {
                            Id = 4,
                            Name = "اسباب کشی و باربری"
                        },
                        new
                        {
                            Id = 5,
                            Name = "لوازم خانگی"
                        },
                        new
                        {
                            Id = 6,
                            Name = "خدمات اداری"
                        },
                        new
                        {
                            Id = 7,
                            Name = "نظافت و بهداشت"
                        },
                        new
                        {
                            Id = 8,
                            Name = "دیجیتال و نرم افزار"
                        },
                        new
                        {
                            Id = 9,
                            Name = "پزشکی و سلامت"
                        });
                });

            modelBuilder.Entity("Core_HomeService.Domain.Core.CityAgg.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "تهران",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "اسلامشهر",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "ری",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "اصفهان",
                            ProvinceId = 2
                        },
                        new
                        {
                            Id = 5,
                            Name = "کاشان",
                            ProvinceId = 2
                        },
                        new
                        {
                            Id = 6,
                            Name = "نجف‌آباد",
                            ProvinceId = 2
                        },
                        new
                        {
                            Id = 7,
                            Name = "مشهد",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 8,
                            Name = "نیشابور",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 9,
                            Name = "سبزوار",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 10,
                            Name = "شیراز",
                            ProvinceId = 4
                        },
                        new
                        {
                            Id = 11,
                            Name = "مرودشت",
                            ProvinceId = 4
                        },
                        new
                        {
                            Id = 12,
                            Name = "جهرم",
                            ProvinceId = 4
                        },
                        new
                        {
                            Id = 13,
                            Name = "اهواز",
                            ProvinceId = 5
                        },
                        new
                        {
                            Id = 14,
                            Name = "آبادان",
                            ProvinceId = 5
                        },
                        new
                        {
                            Id = 15,
                            Name = "دزفول",
                            ProvinceId = 5
                        },
                        new
                        {
                            Id = 16,
                            Name = "ساری",
                            ProvinceId = 6
                        },
                        new
                        {
                            Id = 17,
                            Name = "بابل",
                            ProvinceId = 6
                        },
                        new
                        {
                            Id = 18,
                            Name = "آمل",
                            ProvinceId = 6
                        },
                        new
                        {
                            Id = 19,
                            Name = "رشت",
                            ProvinceId = 7
                        },
                        new
                        {
                            Id = 20,
                            Name = "انزلی",
                            ProvinceId = 7
                        },
                        new
                        {
                            Id = 21,
                            Name = "لاهیجان",
                            ProvinceId = 7
                        },
                        new
                        {
                            Id = 22,
                            Name = "گرگان",
                            ProvinceId = 8
                        },
                        new
                        {
                            Id = 23,
                            Name = "گنبد کاووس",
                            ProvinceId = 8
                        },
                        new
                        {
                            Id = 24,
                            Name = "آق‌قلا",
                            ProvinceId = 8
                        },
                        new
                        {
                            Id = 25,
                            Name = "تبریز",
                            ProvinceId = 9
                        },
                        new
                        {
                            Id = 26,
                            Name = "مراغه",
                            ProvinceId = 9
                        },
                        new
                        {
                            Id = 27,
                            Name = "میانه",
                            ProvinceId = 9
                        },
                        new
                        {
                            Id = 28,
                            Name = "سنندج",
                            ProvinceId = 10
                        },
                        new
                        {
                            Id = 29,
                            Name = "قروه",
                            ProvinceId = 10
                        },
                        new
                        {
                            Id = 30,
                            Name = "بانه",
                            ProvinceId = 10
                        },
                        new
                        {
                            Id = 31,
                            Name = "کرمان",
                            ProvinceId = 11
                        },
                        new
                        {
                            Id = 32,
                            Name = "سیرجان",
                            ProvinceId = 11
                        },
                        new
                        {
                            Id = 33,
                            Name = "بم",
                            ProvinceId = 11
                        },
                        new
                        {
                            Id = 34,
                            Name = "یزد",
                            ProvinceId = 12
                        },
                        new
                        {
                            Id = 35,
                            Name = "میبد",
                            ProvinceId = 12
                        },
                        new
                        {
                            Id = 36,
                            Name = "اردکان",
                            ProvinceId = 12
                        });
                });

            modelBuilder.Entity("Core_HomeService.Domain.Core.CommentAgg.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("ExpertId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ExpertId");

                    b.HasIndex("RequestId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Core_HomeService.Domain.Core.ImageAgg.Entities.RequestImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.ToTable("RequestImages");
                });

            modelBuilder.Entity("Core_HomeService.Domain.Core.OfferAgg.Entities.Offer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("ExpertId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ExpertId");

                    b.HasIndex("RequestId");

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("Core_HomeService.Domain.Core.ProvinceAgg.Entities.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Provinces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "تهران"
                        },
                        new
                        {
                            Id = 2,
                            Name = "اصفهان"
                        },
                        new
                        {
                            Id = 3,
                            Name = "خراسان رضوی"
                        },
                        new
                        {
                            Id = 4,
                            Name = "فارس"
                        },
                        new
                        {
                            Id = 5,
                            Name = "خوزستان"
                        },
                        new
                        {
                            Id = 6,
                            Name = "مازندران"
                        },
                        new
                        {
                            Id = 7,
                            Name = "گیلان"
                        },
                        new
                        {
                            Id = 8,
                            Name = "گلستان"
                        },
                        new
                        {
                            Id = 9,
                            Name = "آذربایجان شرقی"
                        },
                        new
                        {
                            Id = 10,
                            Name = "کردستان"
                        },
                        new
                        {
                            Id = 11,
                            Name = "کرمان"
                        },
                        new
                        {
                            Id = 12,
                            Name = "یزد"
                        });
                });

            modelBuilder.Entity("Core_HomeService.Domain.Core.RequestAgg.Entities.Request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("Core_HomeService.Domain.Core.SubCategoryAgg.Entities.ExpertSubCategory", b =>
                {
                    b.Property<int>("ExpertId")
                        .HasColumnType("int");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.HasKey("ExpertId", "SubCategoryId");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("ExpertSubCategories");
                });

            modelBuilder.Entity("Core_HomeService.Domain.Core.SubCategoryAgg.Entities.SubCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("SubCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasePrice = 500000m,
                            CategoryId = 1,
                            Description = "انجام عملیات بنایی و ساخت دیوار، آجرکاری و تسطیح سطوح",
                            Name = "بنایی"
                        },
                        new
                        {
                            Id = 2,
                            BasePrice = 700000m,
                            CategoryId = 1,
                            Description = "طراحی و اجرای دکوراسیون داخلی، نصب دیوارپوش و عناصر تزئینی",
                            Name = "دکوراسیون"
                        },
                        new
                        {
                            Id = 3,
                            BasePrice = 400000m,
                            CategoryId = 1,
                            Description = "رنگ‌آمیزی سطوح داخلی و خارجی با رنگ‌های باکیفیت",
                            Name = "نقاشی ساختمان"
                        },
                        new
                        {
                            Id = 4,
                            BasePrice = 600000m,
                            CategoryId = 1,
                            Description = "نصب و تعمیر انواع درب و پنجره با دقت و آب‌بندی مناسب",
                            Name = "درب و پنجره"
                        },
                        new
                        {
                            Id = 5,
                            BasePrice = 800000m,
                            CategoryId = 1,
                            Description = "انجام کارهای فلزی، جوشکاری و ساخت نرده و حفاظ",
                            Name = "آهنگری و جوشکاری"
                        },
                        new
                        {
                            Id = 6,
                            BasePrice = 300000m,
                            CategoryId = 1,
                            Description = "طراحی و نگهداری فضای سبز و چمن‌کاری",
                            Name = "باغبانی"
                        },
                        new
                        {
                            Id = 7,
                            BasePrice = 900000m,
                            CategoryId = 2,
                            Description = "نصب و سرویس سیستم‌های کولر و بخاری",
                            Name = "سرمایش و گرمایش"
                        },
                        new
                        {
                            Id = 8,
                            BasePrice = 650000m,
                            CategoryId = 2,
                            Description = "نصب و تعمیر لوله‌های آب و فاضلاب",
                            Name = "لوله کشی"
                        },
                        new
                        {
                            Id = 9,
                            BasePrice = 550000m,
                            CategoryId = 2,
                            Description = "خدمات برق‌کشی و نصب تجهیزات الکتریکی",
                            Name = "برق و الکترونیک"
                        },
                        new
                        {
                            Id = 10,
                            BasePrice = 750000m,
                            CategoryId = 2,
                            Description = "نصب و راه‌اندازی سیستم‌های تلفن و سانترال",
                            Name = "تلفن و سانترال"
                        },
                        new
                        {
                            Id = 11,
                            BasePrice = 1000000m,
                            CategoryId = 3,
                            Description = "تعمیر و سرویس خودروهای سبک و سنگین",
                            Name = "خودرو"
                        },
                        new
                        {
                            Id = 12,
                            BasePrice = 1200000m,
                            CategoryId = 4,
                            Description = "حمل ایمن اسباب و بسته‌بندی وسایل",
                            Name = "اسباب کشی"
                        },
                        new
                        {
                            Id = 13,
                            BasePrice = 800000m,
                            CategoryId = 4,
                            Description = "حمل بار شهری با تجهیزات مناسب",
                            Name = "حمل بار"
                        },
                        new
                        {
                            Id = 14,
                            BasePrice = 600000m,
                            CategoryId = 5,
                            Description = "نصب و تعمیر لوازم آشپزخانه",
                            Name = "لوازم آشپزخانه"
                        },
                        new
                        {
                            Id = 15,
                            BasePrice = 550000m,
                            CategoryId = 5,
                            Description = "تعمیر تجهیزات شستشو و نظافتی",
                            Name = "لوازم شست و شو و نظافت"
                        },
                        new
                        {
                            Id = 16,
                            BasePrice = 650000m,
                            CategoryId = 5,
                            Description = "نصب و تعمیر سیستم‌های صوتی و تصویری",
                            Name = "لوازم صوتی و تصویری"
                        },
                        new
                        {
                            Id = 17,
                            BasePrice = 700000m,
                            CategoryId = 6,
                            Description = "خدمات تعمیر و نگهداری ماشین‌های اداری",
                            Name = "ماشین اداری"
                        },
                        new
                        {
                            Id = 18,
                            BasePrice = 900000m,
                            CategoryId = 6,
                            Description = "نصب و تعمیر مبلمان و تجهیزات اداری",
                            Name = "مبلمان اداری"
                        },
                        new
                        {
                            Id = 19,
                            BasePrice = 400000m,
                            CategoryId = 7,
                            Description = "نظافت حرفه‌ای منزل و محل کار",
                            Name = "نظافت"
                        },
                        new
                        {
                            Id = 20,
                            BasePrice = 500000m,
                            CategoryId = 7,
                            Description = "شستشوی حرفه‌ای فرش و مبلمان",
                            Name = "خشکشویی و قالیشویی"
                        },
                        new
                        {
                            Id = 21,
                            BasePrice = 600000m,
                            CategoryId = 7,
                            Description = "شستشو و پاکسازی فرش و مبل تهیه‌شده",
                            Name = "قالیشویی و مبل شویی"
                        },
                        new
                        {
                            Id = 22,
                            BasePrice = 450000m,
                            CategoryId = 7,
                            Description = "سمپاشی حرفه‌ای برای دفع آفات",
                            Name = "سمپاشی"
                        },
                        new
                        {
                            Id = 23,
                            BasePrice = 700000m,
                            CategoryId = 8,
                            Description = "تعمیر موبایل و تبلت با قطعات استاندارد",
                            Name = "موبایل و تبلت"
                        },
                        new
                        {
                            Id = 24,
                            BasePrice = 650000m,
                            CategoryId = 8,
                            Description = "نصب و راه‌اندازی کامپیوتر و شبکه",
                            Name = "خدمات کامپیوتری"
                        },
                        new
                        {
                            Id = 25,
                            BasePrice = 1200000m,
                            CategoryId = 8,
                            Description = "پیاده‌سازی و پشتیبانی شبکه و امنیت",
                            Name = "امنیت و شبکه"
                        },
                        new
                        {
                            Id = 26,
                            BasePrice = 1500000m,
                            CategoryId = 9,
                            Description = "خدمات پزشکی اولیه در محل",
                            Name = "پزشکی"
                        });
                });

            modelBuilder.Entity("Core_HomeService.Domain.Core.UserAgg.Entities.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<decimal>("AccountBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("ProvinceId");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            AccountBalance = 0m,
                            CityId = 1,
                            ConcurrencyStamp = "2a819d70-95a6-4065-b82f-0d4c1bfd1586",
                            Email = "admin@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "admin",
                            LastName = "admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAECES4VvUlgRpMvdtovIIorqwHFQQADc6bzQILxbwiKJdb1PxL294y2sKOY6X5JtXJw==",
                            PhoneNumberConfirmed = false,
                            ProvinceId = 1,
                            SecurityStamp = "709ddaca-69cc-455f-ae28-8bd9613ab39e",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("Core_HomeService.Domain.Core.UserAgg.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Core_HomeService.Domain.Core.UserAgg.Entities.Expert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Rating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Experts");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "6e728874-4e86-442c-a964-82d9a54de833",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "11d9f16c-d256-4965-aa55-cac9a62569b0",
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        },
                        new
                        {
                            Id = 3,
                            ConcurrencyStamp = "fe9d9b49-9791-4ece-967a-5327cc67c3c2",
                            Name = "Expert",
                            NormalizedName = "EXPERT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Core_HomeService.Domain.Core.CityAgg.Entities.City", b =>
                {
                    b.HasOne("Core_HomeService.Domain.Core.ProvinceAgg.Entities.Province", "Province")
                        .WithMany("Cities")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("Core_HomeService.Domain.Core.CommentAgg.Entities.Comment", b =>
                {
                    b.HasOne("Core_HomeService.Domain.Core.UserAgg.Entities.Customer", "Customer")
                        .WithMany("Comments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core_HomeService.Domain.Core.UserAgg.Entities.Expert", "Expert")
                        .WithMany("Comments")
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core_HomeService.Domain.Core.RequestAgg.Entities.Request", "Request")
                        .WithMany("Comments")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Expert");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("Core_HomeService.Domain.Core.ImageAgg.Entities.RequestImage", b =>
                {
                    b.HasOne("Core_HomeService.Domain.Core.RequestAgg.Entities.Request", "Request")
                        .WithMany("Images")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("Core_HomeService.Domain.Core.OfferAgg.Entities.Offer", b =>
                {
                    b.HasOne("Core_HomeService.Domain.Core.UserAgg.Entities.Expert", "Expert")
                        .WithMany("Offers")
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core_HomeService.Domain.Core.RequestAgg.Entities.Request", "Request")
                        .WithMany("Offers")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Expert");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("Core_HomeService.Domain.Core.RequestAgg.Entities.Request", b =>
                {
                    b.HasOne("Core_HomeService.Domain.Core.CityAgg.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core_HomeService.Domain.Core.UserAgg.Entities.Customer", "Customer")
                        .WithMany("Requests")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core_HomeService.Domain.Core.ProvinceAgg.Entities.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Customer");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("Core_HomeService.Domain.Core.SubCategoryAgg.Entities.ExpertSubCategory", b =>
                {
                    b.HasOne("Core_HomeService.Domain.Core.UserAgg.Entities.Expert", "Expert")
                        .WithMany("ExpertSubCategories")
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core_HomeService.Domain.Core.SubCategoryAgg.Entities.SubCategory", "SubCategory")
                        .WithMany("ExpertSubCategories")
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Expert");

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("Core_HomeService.Domain.Core.SubCategoryAgg.Entities.SubCategory", b =>
                {
                    b.HasOne("Core_HomeService.Domain.Core.CategoryAgg.Entities.Category", "Category")
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Core_HomeService.Domain.Core.UserAgg.Entities.ApplicationUser", b =>
                {
                    b.HasOne("Core_HomeService.Domain.Core.CityAgg.Entities.City", "City")
                        .WithMany("Users")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core_HomeService.Domain.Core.ProvinceAgg.Entities.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("Core_HomeService.Domain.Core.UserAgg.Entities.Customer", b =>
                {
                    b.HasOne("Core_HomeService.Domain.Core.UserAgg.Entities.ApplicationUser", "User")
                        .WithOne("Customer")
                        .HasForeignKey("Core_HomeService.Domain.Core.UserAgg.Entities.Customer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core_HomeService.Domain.Core.UserAgg.Entities.Expert", b =>
                {
                    b.HasOne("Core_HomeService.Domain.Core.UserAgg.Entities.ApplicationUser", "User")
                        .WithOne("Expert")
                        .HasForeignKey("Core_HomeService.Domain.Core.UserAgg.Entities.Expert", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Core_HomeService.Domain.Core.UserAgg.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Core_HomeService.Domain.Core.UserAgg.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core_HomeService.Domain.Core.UserAgg.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Core_HomeService.Domain.Core.UserAgg.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core_HomeService.Domain.Core.CategoryAgg.Entities.Category", b =>
                {
                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("Core_HomeService.Domain.Core.CityAgg.Entities.City", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Core_HomeService.Domain.Core.ProvinceAgg.Entities.Province", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("Core_HomeService.Domain.Core.RequestAgg.Entities.Request", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Images");

                    b.Navigation("Offers");
                });

            modelBuilder.Entity("Core_HomeService.Domain.Core.SubCategoryAgg.Entities.SubCategory", b =>
                {
                    b.Navigation("ExpertSubCategories");
                });

            modelBuilder.Entity("Core_HomeService.Domain.Core.UserAgg.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Customer");

                    b.Navigation("Expert");
                });

            modelBuilder.Entity("Core_HomeService.Domain.Core.UserAgg.Entities.Customer", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Requests");
                });

            modelBuilder.Entity("Core_HomeService.Domain.Core.UserAgg.Entities.Expert", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("ExpertSubCategories");

                    b.Navigation("Offers");
                });
#pragma warning restore 612, 618
        }
    }
}
