<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Core_HomeService.Domain.Core</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="UserAgg\Contracts\AppServiceContracts\CustomerContract\" />
    <Folder Include="UserAgg\Contracts\AppServiceContracts\ExpertContract\" />
    <Folder Include="UserAgg\Contracts\AppServiceContracts\AccountContract\" />
    <Folder Include="UserAgg\Contracts\AppServiceContracts\WalletContract\" />
    <Folder Include="UserAgg\Contracts\ServiceContracts\ExpertContract\" />
    <Folder Include="UserAgg\DTOs\ExpertDTOs\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.1" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.1" />
  </ItemGroup>

</Project>
