<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Core_HomeService.Domain.Core</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="CategoryAgg\Contracts\AppServiceContracts\" />
    <Folder Include="CategoryAgg\Contracts\RepositoryContracts\" />
    <Folder Include="CategoryAgg\Contracts\ServiceContracts\" />
    <Folder Include="CategoryAgg\DTOs\" />
    <Folder Include="CityAgg\Contracts\AppServiceContracts\" />
    <Folder Include="CityAgg\Contracts\RepositoryContracts\" />
    <Folder Include="CityAgg\Contracts\ServiceContracts\" />
    <Folder Include="CityAgg\DTOs\" />
    <Folder Include="CommentAgg\Contracts\AppServiceContracts\" />
    <Folder Include="CommentAgg\Contracts\RepositoryContracts\" />
    <Folder Include="CommentAgg\Contracts\ServiceContracts\" />
    <Folder Include="CommentAgg\DTOs\" />
    <Folder Include="ImageAgg\Contracts\AppServiceContracts\" />
    <Folder Include="ImageAgg\Contracts\RepositoryContracts\" />
    <Folder Include="ImageAgg\Contracts\ServiceContracts\" />
    <Folder Include="ImageAgg\DTOs\" />
    <Folder Include="OfferAgg\Contracts\AppServiceContracts\" />
    <Folder Include="OfferAgg\Contracts\RepositoryContracts\" />
    <Folder Include="OfferAgg\Contracts\ServiceContracts\" />
    <Folder Include="OfferAgg\DTOs\" />
    <Folder Include="ProvinceAgg\Contracts\AppServiceContracts\" />
    <Folder Include="ProvinceAgg\Contracts\RepositoryContracts\" />
    <Folder Include="ProvinceAgg\Contracts\ServiceContracts\" />
    <Folder Include="ProvinceAgg\DTOs\" />
    <Folder Include="RequestAgg\Contracts\AppServiceContracts\" />
    <Folder Include="RequestAgg\Contracts\RepositoryContracts\" />
    <Folder Include="RequestAgg\Contracts\ServiceContracts\" />
    <Folder Include="RequestAgg\DTOs\" />
    <Folder Include="SubCategoryAgg\Contracts\AppServiceContracts\" />
    <Folder Include="SubCategoryAgg\Contracts\RepositoryContracts\" />
    <Folder Include="SubCategoryAgg\Contracts\ServiceContracts\" />
    <Folder Include="SubCategoryAgg\DTOs\" />
    <Folder Include="UserAgg\Contracts\AppServiceContracts\" />
    <Folder Include="UserAgg\Contracts\ServiceContracts\" />
    <Folder Include="UserAgg\Contracts\RepositoryContracts\" />
    <Folder Include="UserAgg\DTOs\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.1" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.1" />
  </ItemGroup>

</Project>
